### ISSUE TITLE
[Question] Merge your module with the one recently created by the midi community ?

### ISSUE THREAD

**Issue by p4535992** [gambit07/gambits-premades#1]
Do you think it makes sense to try to merge your module with the one recently created by the midi community https://github.com/txm3278/midi-item-showcase-community ?

**Comment by gambit07** [comment]
No, I think it makes more sense for me to do upkeep on it with the amount of updates and releases I do, I chatted with tminz about this being in misc initially though. Additionally, I'm planning to build some features into the module itself for more complicated automations like Counterspell and Opportunity Attacks

**Comment by MotoMoto1234** [comment]
> Do you think it makes sense to try to merge your module with the one recently created by the midi community https://github.com/txm3278/midi-item-showcase-community ?

With Chris' premades module there is a setting called Additional Compendiums, you can simply just wrack in all the other premade modules into this setting and everything behaves as if it was in CPR:  

![image](https://github.com/gambit07/gambits-premades/assets/116308065/6b7c1cab-6d41-4c27-911a-9bd5b57a25e8)

**Comment by p4535992** [comment]
> > Do you think it makes sense to try to merge your module with the one recently created by the midi community https://github.com/txm3278/midi-item-showcase-community ?
> 
> With Chris' premades module there is a setting called Additional Compendiums, you can simply just wrack in all the other premade modules into this setting and everything behaves as if it was in CPR:
> 
> ![image](https://private-user-images.githubusercontent.com/116308065/300630946-6b7c1cab-6d41-4c27-911a-9bd5b57a25e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDg2MjcsIm5iZiI6MTcwNjYwODMyNywicGF0aCI6Ii8xMTYzMDgwNjUvMzAwNjMwOTQ2LTZiN2MxY2FiLTZkNDEtNGMyNy05MTFhLTliZDViNTdhMjVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwOTUyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzQ4ZDlhYjJlMzQ1NzMwMGIwYTIyNWYwNmJlZDg5ODM5ZDg1MDI4YTZiOWYxY2QxOTk2OGI3N2YzMGM5Mzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o8K09673PnjI6GWt7k0w75Z_akQk8Qd8Gj5h8WgeDGw)

Interesting didn't know it that ! Ty @MotoMoto1234

**Comment by MotoMoto1234** [comment]
> > > Do you think it makes sense to try to merge your module with the one recently created by the midi community https://github.com/txm3278/midi-item-showcase-community ?
> > 
> > 
> > With Chris' premades module there is a setting called Additional Compendiums, you can simply just wrack in all the other premade modules into this setting and everything behaves as if it was in CPR:
> > ![image](https://private-user-images.githubusercontent.com/116308065/300630946-6b7c1cab-6d41-4c27-911a-9bd5b57a25e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDg2MjcsIm5iZiI6MTcwNjYwODMyNywicGF0aCI6Ii8xMTYzMDgwNjUvMzAwNjMwOTQ2LTZiN2MxY2FiLTZkNDEtNGMyNy05MTFhLTliZDViNTdhMjVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwOTUyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzQ4ZDlhYjJlMzQ1NzMwMGIwYTIyNWYwNmJlZDg5ODM5ZDg1MDI4YTZiOWYxY2QxOTk2OGI3N2YzMGM5Mzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o8K09673PnjI6GWt7k0w75Z_akQk8Qd8Gj5h8WgeDGw)
> 
> Interesting didn't know it that ! Ty @MotoMoto1234

Also the 3 of them got together and added further integration, so that the monster updater would work better.  Not fully rolled out yet on each one bug CPR's laid the groundwork for it.
