### ISSUE TITLE
[Bug] Jim's Magic Missile macro fails with eval warning after 3 attacks are rolled

### ISSUE THREAD

**Issue by gt-j** [gambit07/gambits-premades#11]
Foundry: 11.315
DND5e : 3.04
Midi QOL: 11.4.10
GP: 0.0.99

![image](https://github.com/gambit07/gambits-premades/assets/51988167/5d4f53a0-ae99-4849-a7e4-83fbd12ee103)

**Comment by gambit07** [comment]
tracking in #12
