### ISSUE TITLE
Configure item names

### ISSUE THREAD

**Issue by Talanor** [gambit07/gambits-premades#13]
Hello, thanks for all the work you put into this collection !
I play in another language, would it be possible for you to:

1) Provide international support by using babele or equivalent ?
2) Provide a way to configure items / skills names: For example, in ItemMacro for opportunity attack, you check for specific names (`effectOriginActor.items.getName("Sentinel")` for example)
Wild Magic Surges 5e fixes that by enabling GMs to put arbitrary names in the feature's settings like so:
![image](https://github.com/gambit07/gambits-premades/assets/2121473/0e01b589-8740-454e-8d9e-46cff4b00c8c)

Best !

**Comment by gambit07** [comment]
> Hello, thanks for all the work you put into this collection ! I play in another language, would it be possible for you to:
> 
>     1. Provide international support by using babele or equivalent ?
> 
>     2. Provide a way to configure items / skills names: For example, in ItemMacro for opportunity attack, you check for specific names (`effectOriginActor.items.getName("Sentinel")` for example)
>        Wild Magic Surges 5e fixes that by enabling GMs to put arbitrary names in the feature's settings like so:
>        ![image](https://private-user-images.githubusercontent.com/2121473/314067322-0e01b589-8740-454e-8d9e-46cff4b00c8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Njc2MTMsIm5iZiI6MTcxMDg2NzMxMywicGF0aCI6Ii8yMTIxNDczLzMxNDA2NzMyMi0wZTAxYjU4OS04NzQwLTQ1NGUtOGQ5ZS00NmNmZjRiMDBjOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTY1NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODIxODAyYzYxMDgwZDE4NDBjNzk0YjU2N2Y3ZDI4NTRmNzkxYzQzZDRjY2I1NDkxMDExYWVlOTk0OGUzN2EzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ig8CTArPb6wKKaL_GEze0WGmpCslAia583_CaBdrSw0)
> 
> 
> Best !

I believe chrome's updated translate feature does a good job of an on the fly translation overlay. That being said, I'll see what I can do about adding native localization support.
