### ISSUE TITLE
About Counterspell and Silvery Barb

### ISSUE THREAD

**Issue by TOUHOUCON** [gambit07/gambits-premades#14]
Would it be possible to change the name lookup for **Counterspell** and **Silvery Barb** from strictly equal to include English fields? It's friendly to non-English speaking players

**Comment by gambit07** [comment]
> Would it be possible to change the name lookup for **Counterspell** and **Silvery Barb** from strictly equal to include English fields? It's friendly to non-English speaking players

Hi, what do you mean by include English fields?

**Comment by TOUHOUCON** [comment]
I found that the code in counterspell.js is checking to see if the character has a spell named 「counterspell」 on them. This does not detect spells with names like 「対抗呪文 conterspell」. Is it possible to make it so that the name contains 「conterspell」 instead of having to be 「conterspell」?

**Comment by gambit07** [comment]
Hm, I don't like doing contains as it could catch homebrews that aren't meant to trigger the feature. These are fairly unique so I'll think about it
