### ISSUE TITLE
 Organizing Compendiums into Folders

### ISSUE THREAD

**Issue by maekzi** [gambit07/gambits-premades#16]
**Request: Organizing Compendiums into Folders**

**Description:**
I propose organizing compendiums into folders for better organization and ease of navigation. Currently, I am unable to fork the repository and create a pull request, so I'm presenting my suggested changes here.

**Suggested Changes:**
- Create a dedicated folder for compendiums.
- Move existing compendium files into the newly created folder.

```json
"packFolders": [
    {
      "name": "Gambit's Premades",
      "sorting": "m",
      "color": "",
      "packs": [
        "gps-spells",
        "gps-class-features",
        "gps-items",
        "gps-monster-features",
        "gps-generic-features",
        "gps-homebrew-features",
        "gps-homebrew-items",
        "gps-homebrew-spells",
        "gps-actors"
      ]
    }
  ],
```

Thank you for considering. Have a great day!

**Comment by gambit07** [comment]
> **Request: Organizing Compendiums into Folders**
> 
> **Description:** I propose organizing compendiums into folders for better organization and ease of navigation. Currently, I am unable to fork the repository and create a pull request, so I'm presenting my suggested changes here.
> 
> **Suggested Changes:**
> 
>     * Create a dedicated folder for compendiums.
> 
>     * Move existing compendium files into the newly created folder.
> 
> 
> ```json
> "packFolders": [
>     {
>       "name": "Gambit's Premades",
>       "sorting": "m",
>       "color": "",
>       "packs": [
>         "gps-spells",
>         "gps-class-features",
>         "gps-items",
>         "gps-monster-features",
>         "gps-generic-features",
>         "gps-homebrew-features",
>         "gps-homebrew-items",
>         "gps-homebrew-spells",
>         "gps-actors"
>       ]
>     }
>   ],
> ```
> 
> Thank you for considering. Have a great day!

Hey yeah I can do this, I hadn't done it because core has an annoying bug where moving compendiums out of the folder and deleting it will still cause the folder to be re-created on a world restart and I didn't want to contribute to folder bloat with that. A few people have asked for it now though, so I'll probably go ahead and add one in

**Comment by gambit07** [comment]
This will be added in .1.9
