### ISSUE TITLE
Attack of Opportunity feature request

### ISSUE THREAD

**Issue by franckflo** [gambit07/gambits-premades#17]
Hi, I love this feature, but I'm not very found of the templates that are automatically created when the combat starts. Would you be able to add some settings in Gambit's Premades that allow GMs to choose the opacity of the template created, and whether or not the line around it is visible, and maybe even hide it altogether. This would allow much more flexibility :). When there are a lot of combatants in close combat, the templates tend to blend in and hide the map below. 

Thanks a lot !

**Comment by gambit07** [comment]
> Hi, I love this feature, but I'm not very found of the templates that are automatically created when the combat starts. Would you be able to add some settings in Gambit's Premades that allow GMs to choose the opacity of the template created, and whether or not the line around it is visible, and maybe even hide it altogether. This would allow much more flexibility :). When there are a lot of combatants in close combat, the templates tend to blend in and hide the map below.
> 
> Thanks a lot !

Thanks! This is actually already enabled if you install the Walled Templates module. Walled Templates is configured within the automations code to completely hide the template when installed

**Comment by franckflo** [comment]
Wouldn't making that a change potentially affect other modules than yours if they also use Walled templates, like MIDI QoL for example? Also, do you know of a way of keeping the template generated by Attack of Opportunity, but edit the opacity or color of the templates?

**Comment by gambit07** [comment]
Not sure exactly what you mean but Walled Templates is essentially making the template invisible, the template still exists on the canvas as normal though. This is applied at the template level so you don't need to make other spell templates etc invisible if you don't want to

**Comment by franckflo** [comment]
I see, obviously I didn't understand how Wall Templates works. 

Now, do you think it's be possible to customize the appearance (opacity, color, etc) of the templates generated by Gambit's ?

**Comment by gambit07** [comment]
No prob! Yes if you wish to modify the template highlighting instead you can do so in the DIME macro on the compendium item. This would need to be updated after each update though if you're modifying it yourself

**Comment by franckflo** [comment]
Sounds good, I'll look into it!
