### ISSUE TITLE
Reach Weapons

### ISSUE THREAD

**Issue by webmaster94** [gambit07/gambits-premades#18]
The oppurtunity attack feature does not appear to take into account reach weapons for either walking away or moving towards a person who has the polearm master feat. It prompts at 5 feet when it should prompt at 10 feet.

**Comment by gambit07** [comment]
> The oppurtunity attack feature does not appear to take into account reach weapons for either walking away or moving towards a person who has the polearm master feat. It prompts at 5 feet when it should prompt at 10 feet. 

Is this for an actor using a spear?

**Comment by webmaster94** [comment]
Yes it is.

**Comment by gambit07** [comment]
> Yes it is. 

Gotcha, a spear doesn't have the reach property so 5 feet would be correct

**Comment by webmaster94** [comment]
I'm aware of that. However, I allow it to be reached when they're using two hands. But why is it using name matching? Shouldn't it just be matching the reach property that exists on the weapon? It's rather intolerant of Homebrew if it is doing name matching.

**Comment by gambit07** [comment]
My suggestion would be to give them a 'Melee Spear' secondary weapon that has a 10 foot range. The weapons range is based on its range property, thrown type weapons have their thrown range not melee range so it defaults to 5 feet

**Comment by webmaster94** [comment]
Ok so it uses the range field within the weapon and the thrown flag causes it to just default to five feet. That makes a lot more sense and you may want to consider documenting that in the readme. I can modify that. They neve throw their spear anyway. Will confirm once removing the thrown property and setting the range to ten feet, that the feature is working as expected.
