### ISSUE TITLE
Walled Templates Issue 

### ISSUE THREAD

**Issue by NdranC** [gambit07/gambits-premades#19]
I have a issue between Walled Templates, Chris's Premades, Gambit's Premades and sightly Drag Ruler. I posted this issue first at Chris's Premades and they recommended for me to post it here.

Here is a video showcasing my problem https://youtu.be/1GCY0k10jsY

If I use all 4 mods together, I start having issues dragging tokens to move and the darkness spell breaks completely.

If I disable Walled Templates everything works just fine.

I suspect some of these issues are not solely on Walled Templates but also the templates created by Gambit's to track attacks of opportunities. I figured I would post here since this issue sounds very similar to my own.

Versions:
Dnd 5e 3.1.2
Walled Templates 7.10
Chris's 0.10.73
Gambit's 0.1.41
Drag Ruler 1.13.8

**Comment by gambit07** [comment]
> I have a issue between Walled Templates, Chris's Premades, Gambit's Premades and sightly Drag Ruler. I posted this issue first at Chris's Premades and they recommended for me to post it here.
> 
> Here is a video showcasing my problem https://youtu.be/1GCY0k10jsY
> 
> If I use all 4 mods together, I start having issues dragging tokens to move and the darkness spell breaks completely.
> 
> If I disable Walled Templates everything works just fine.
> 
> I suspect some of these issues are not solely on Walled Templates but also the templates created by Gambit's to track attacks of opportunities. I figured I would post here since this issue sounds very similar to my own.
> 
> Versions: Dnd 5e 3.1.2 Walled Templates 7.10 Chris's 0.10.73 Gambit's 0.1.41 Drag Ruler 1.13.8

In order to use Drag Ruler, you must enable the 'Enable Opportunity Attack Legacy System' setting in the module

**Comment by NdranC** [comment]
Hi there. Just to be clear I can use Drag Ruler with and without the legacy setting and everything works just fine. The problem is when I enable Walled Templates. Both with the legacy setting on and off I have issues.

With legacy setting on and walled templates on, I can drag the tokens normally but attacks of opportunity cease to work.

With legacy setting off and walled templates on, I have the dragging issues shown in the video.

With legacy setting on and walled templates off everything seem to work fine.l

With legacy setting off and walled templates off everything seem to work fine despite having drag ruler enabled.

All these test were run with drag ruler. As far as I can tell turning it off does nothing for me.

**Comment by gambit07** [comment]
> Hi there. Just to be clear I can use Drag Ruler with and without the legacy setting and everything works just fine. The problem is when I enable Walled Templates. Both with the legacy setting on and off I have issues.
> 
> With legacy setting on and walled templates on, I can drag the tokens normally but attacks of opportunity cease to work.
> 
> With legacy setting off and walled templates on, I have the dragging issues shown in the video.
> 
> With legacy setting on and walled templates off everything seem to work fine.l
> 
> With legacy setting off and walled templates off everything seem to work fine despite having drag ruler enabled.
> 
> All these test were run with drag ruler. As far as I can tell turning it off does nothing for me.
> 
> EDIT: Completely uninstalling drag ruler and replacing it with the new elevator ruler seem to have delt with the draggin issues. I guess the issue just became, "legacy setting doesn't work with drag ruler and walled templates combined" but since you are planning to face it out anyway it's probably not worth worrying about it.
> 
> Than you.

Thanks for the info, I'll do some testing and see what I find out

**Comment by NdranC** [comment]
Hi, sorry to bother you again but I'm still having issues with Walled Templates but in ways unrelated to your mod. I guess what I want to know is if you recommend a mod to hide the templates around tokens when playing with automated attacks of opportunity because that is the main reason as to why I decided to install Walled Templates.

I assume this is a common issue/request when playing with that feature enabled. Thanks.

**Comment by gambit07** [comment]
> Hi, sorry to bother you again but I'm still having issues with Walled Templates but in ways unrelated to your mod. I guess what I want to know is if you recommend a mod to hide the templates around tokens when playing with automated attacks of opportunity because that is the main reason as to why I decided to install Walled Templates.
> 
> I assume this is a common issue/request when playing with that feature enabled. Thanks.

No worries, Walled Templates is the only module capable of fully hiding templates right now. I believe a couple bugs were introduced in the last update so I'm communicating with caewok to try and get them resolved
