### ISSUE TITLE
Oppurtunity Attack shows a permission error for players

### ISSUE THREAD

**Issue by BrendanBetheldo** [gambit07/gambits-premades#20]
Hi Gambit, very strange issue. Basically when a player triggers the Oppurunity attack trigger they see a permission issue come up on screen.
![image](https://github.com/gambit07/gambits-premades/assets/12805720/99294e30-b033-41eb-8be2-a6c923109f60)

I've narrowed it down to Warpgate and I've given my players all the below permissions as trusted players and given them every permission bar modifying the modules. 

I''ve also go access to Midi Troubleshooter which seems to point me to Warpgate but, again I've got permissions for all players.
[fvtt-midi-qol-troubleshooter.json](https://github.com/gambit07/gambits-premades/files/15342271/fvtt-midi-qol-troubleshooter.json)

Let me know if you need more context.

**Comment by gambit07** [comment]
> Hi Gambit, very strange issue. Basically when a player triggers the Oppurunity attack trigger they see a permission issue come up on screen.
> ![image](https://github.com/gambit07/gambits-premades/assets/12805720/99294e30-b033-41eb-8be2-a6c923109f60)
> 
> I've narrowed it down to Warpgate and I've given my players all the below permissions as trusted players and given them every permission bar modifying the modules. 
> 
> I''ve also go access to Midi Troubleshooter which seems to point me to Warpgate but, again I've got permissions for all players.
> [fvtt-midi-qol-troubleshooter.json](https://github.com/gambit07/gambits-premades/files/15342271/fvtt-midi-qol-troubleshooter.json)
> 
> Let me know if you need more context. 

Hey no problem, this is an issue with Walled Templates actually. I have a fix to prevent it from occurring that will be in the next release

**Comment by BrendanBetheldo** [comment]
> Hey no problem, this is an issue with Walled Templates actually. I have a fix to prevent it from occurring that will be in the next release

Thanks mate, appreciate the fast reply.
