### ISSUE TITLE
Can't Seem to get Opportunity Attack to work

### ISSUE THREAD

**Issue by KellethDregar** [gambit07/gambits-premades#21]
Not sure what I'm doing wrong I've tested both with modules on and then only with the main module and dependencies and it still seems to not behave like it should. It just seems to drop a prompt in the chat and nothing further follows. 

Dnd5e: v3.2.1
Gambit: v0.1.72

![image](https://github.com/user-attachments/assets/c9635687-69d3-476e-aad5-e0318fc1d2eb)
![image](https://github.com/user-attachments/assets/1d16e23a-fc07-49c1-a34d-2ae386418b0d)

Update: 
Found this error in the console when enabling debug.
![image](https://github.com/user-attachments/assets/b2e6bdde-c30c-4c0e-846d-68858619c66b)

**Comment by gambit07** [comment]
> Not sure what I'm doing wrong I've tested both with modules on and then only with the main module and dependencies and it still seems to not behave like it should. It just seems to drop a prompt in the chat and nothing further follows. 
> 
> Dnd5e: v3.2.1
> Gambit: v0.1.72
> 
> ![image](https://github.com/user-attachments/assets/c9635687-69d3-476e-aad5-e0318fc1d2eb)
> ![image](https://github.com/user-attachments/assets/1d16e23a-fc07-49c1-a34d-2ae386418b0d)
> 
> 
> Update: 
> Found this error in the console when enabling debug.
> ![image](https://github.com/user-attachments/assets/b2e6bdde-c30c-4c0e-846d-68858619c66b)
> 
> 

Hi there, this is an issue on the latest midi qol. Reverting to 11.4.40.1 will work, Midi should have an update soon to resolve the issue as well

**Comment by KellethDregar** [comment]
Ah that makes sense, yeah its working now! Is this the case for the other automations like counterspell as well? Was testing some of those earlier and having issues with them as well. Will keep an eye on the updates for midi to see when they update to support these.

**Comment by gambit07** [comment]
> Ah that makes sense, yeah its working now! Is this the case for the other automations like counterspell as well? Was testing some of those earlier and having issues with them as well. Will keep an eye on the updates for midi to see when they update to support these.

Yep! Midi broke some things with the reaction condition in .41, so any of my reaction automations would be effected

**Comment by KellethDregar** [comment]
Ah ok that makes sense! Thank you for explaining!
