### ISSUE TITLE
Dependencies - Warp Gate and Template Macro

### ISSUE THREAD

**Issue by Envaris-Avalon** [gambit07/gambits-premades#22]
Hi,

It seems that neither Warp Gate (honey badger pulled it from github and Foundry) or Template Macro are actively being worked on.  Should they be listed as dependencies anymore in the readme?

Just thought I'd raise it.

Thanks for the hard work!

**Comment by gambit07** [comment]
Thanks, I added in separate V11 and V12 dependency lists
