### ISSUE TITLE
Latest Release Fails to Install

### ISSUE THREAD

**Issue by kajishun** [gambit07/gambits-premades#23]
Looks like there is a malforned URL for the latest release of Gambit's Premades. Two // before module.zip.

![image](https://github.com/user-attachments/assets/d4561549-c760-4d0e-a5f0-73793a7a7189)

**Comment by kajishun** [comment]
or perhaps missing /main?

**Comment by gambit07** [comment]
Indeed, trying to get a more automated versioning process in place 😅
