### ISSUE TITLE
Module bug

### ISSUE THREAD

**Issue by Backp0nd** [gambit07/gambits-premades#25]
I'm using v12 of foundry, the module suddenly got an error and won't let me turn on.

I saw you put up an update for it. I tried installing it but it says it has a bug. But when I try to see if there's a bug. It doesn't find one and it still won't let me active it
<img width="912" alt="bug" src="https://github.com/user-attachments/assets/3a1362a6-5ddf-414b-9f88-564811180050">

Here's what I kept receiving whenever I try to up date it or anything ^

**Comment by gambit07** [comment]
> I'm using v12 of foundry, the module suddenly got an error and won't let me turn on.
> 
> I saw you put up an update for it. I tried installing it but it says it has a bug. But when I try to see if there's a bug. It doesn't find one and it still won't let me active it
> <img width="912" alt="bug" src="https://github.com/user-attachments/assets/3a1362a6-5ddf-414b-9f88-564811180050">
> 
> 
> Here's what I kept receiving whenever I try to up date it or anything ^

Hey there, try uninstalling the module completely and reinstalling

**Comment by Backp0nd** [comment]
So, I tried uninstalling the module completely and reinstalling. I gave me the same problem and everything, I tried just installing the update before anything and it still gave me the same error. then I uninstalled it again and reinstalled it normally with the same error.

**Comment by gambit07** [comment]
> So, I tried uninstalling the module completely and reinstalling. I gave me the same problem and everything, I tried just installing the update before anything and it still gave me the same error. then I uninstalled it again and reinstalled it normally with the same error.

Ah, you need Bugbears Scripts, it's a dependency of the module. If you install that you should be good to go
