### ISSUE TITLE
The module won't install.

### ISSUE THREAD

**Issue by rageance07** [gambit07/gambits-premades#26]

**Comment by rageance07** [comment]
I uninstalled it and reinstalled already still nothing

**Comment by gambit07** [comment]
> I uninstalled it and reinstalled already still nothing

This could be related to this issue: https://github.com/gambit07/gambits-premades/issues/27

I'll have an update likely later today with a fix for that so give it a shot then

**Comment by gambit07** [comment]
> I uninstalled it and reinstalled already still nothing

This should be resolved in the latest update
