### ISSUE TITLE
Dependancy Issue

### ISSUE THREAD

**Issue by Squirrelydood** [gambit07/gambits-premades#27]
The module doesn't read it's dependencies correctly, on install it asks for Bugbear's to be manually installed giving an incorrect manifest url. If bugbear's is installed via the foundry UI this module still doesn't seem to recognize it in the world to allow it to be activated, however it no longer asks for the manual install if Gambit's is deleted and re-installed. As it is the module is quite literally unusable as it cannot be activated despite all the dependencies being met.

**Comment by gambit07** [comment]
Interesting, I'm able to uninstall and re-install currently. Bugbears Scripts manifest was removed on his github though for the version I had in the module, my next update will add in the current manifest link which should resolve this

**Comment by gambit07** [comment]
> The module doesn't read it's dependencies correctly, on install it asks for Bugbear's to be manually installed giving an incorrect manifest url. If bugbear's is installed via the foundry UI this module still doesn't seem to recognize it in the world to allow it to be activated, however it no longer asks for the manual install if Gambit's is deleted and re-installed. As it is the module is quite literally unusable as it cannot be activated despite all the dependencies being met. 

This should be resolved in .5.17
