### ISSUE TITLE
Feature Request :)

### ISSUE THREAD

**Issue by WinterrrWarlock** [gambit07/gambits-premades#28]
Gambit, your work with counterspell has been an absolute game changer. I use Foundry V11 (can't update to 12 because so many things in my world that work haven't been updated and i don't wanna brick things lol) would it be possible for you to automate Entropic Ward? I have a Warlock in my campaign that wants to be able to use it, and when they are struck by a melee attack it prompts the reaction, the problem is that it doesn't intercept the attack and make it roll at disadvantage. I've looked through Chris's Premades and unfortunately they don't have an automation for it either. If there is some way that you know of to intercept the attack and force it re-roll at disadvantage (kinda the same way you did with counterspell providing an opportunity to negate a spell) that would be absolutely amazing. Once again, I'm on V11 and can't update :) 

Thanks for all you do for the Foundry/DND community :)

**Comment by gambit07** [comment]
Thanks! I'm trying to do as little work in the v11 branch as possible, but you're in luck because Entropic Ward is a feature one of my players uses that I'd forgotten to add in. 0.1.78 has it backported from v12, it should work fine in v11 but let me know if you run into any issues

**Comment by gambit07** [comment]
Ah unfortunately after thinking about it, I don't think the backported dialog prompt will work in v11. I'll see if I can find some time to work through it

**Comment by WinterrrWarlock** [comment]
Thank you so much for even looking into it :) hopefully something works out!

**Comment by gambit07** [comment]
> Thank you so much for even looking into it :) hopefully something works out!

Sure thing, I hacked it together for 0.1.79. I think it should be good to go but let me know when you test it

**Comment by WinterrrWarlock** [comment]
You my man are an absolute legend. Works like a charm!! Now I don't have to have her try and remember to say she's using entropic ward BEFORE i roll my attack at her.
