### ISSUE TITLE
Opportunity Attack doesn't show damage button

### ISSUE THREAD

**Issue by terrorbyte704** [gambit07/gambits-premades#29]
https://github.com/user-attachments/assets/1fef3515-7325-468e-81bc-8e05b5bdf5e7

**Comment by terrorbyte704** [comment]
sorry, didn't realise the screen was zoomed in, here is a better one

https://github.com/user-attachments/assets/0519caba-9769-433b-8d9a-fed786d9a2e2

**Comment by gambit07** [comment]
> sorry, didn't realise the screen was zoomed in, here is a better one
> 2024-08-01.17-06-57.mp4

Hi there, try release .20 and see if it resolves your issue

**Comment by terrorbyte704** [comment]
after updating from .19 to .21 it fixes the problem

**Comment by terrorbyte704** [comment]
goodbye
