### ISSUE TITLE
Silvery Barbs does not prompt

### ISSUE THREAD

**Issue by MythicalRollers** [gambit07/gambits-premades#30]
Not sure how much effort you still want to put into V11 but here's hoping.
Foundry: 11.315
D&D: 3.2.1
GP: 1.8.0
Issue:  Silvery Barbs does not prompt at all.  I have the effect enabled in Gambits, I have Chris's Premades looking at GP's compendium set to include everything.  I use the MedKit to update SB on my character sheet, and no reaction prompt.
I did notice under the Midi Qol settings for the MedKit SB, under activation conditions Reaction is set to false.  This is true for a number of spells in the GPS Compendiums.
![image](https://github.com/user-attachments/assets/4d9b88b1-4a37-465e-bacb-14daa775bedd)

**Comment by gambit07** [comment]
> Not sure how much effort you still want to put into V11 but here's hoping.
> Foundry: 11.315
> D&D: 3.2.1
> GP: 1.8.0
> Issue:  Silvery Barbs does not prompt at all.  I have the effect enabled in Gambits, I have Chris's Premades looking at GP's compendium set to include everything.  I use the MedKit to update SB on my character sheet, and no reaction prompt.
> I did notice under the Midi Qol settings for the MedKit SB, under activation conditions Reaction is set to false.  This is true for a number of spells in the GPS Compendiums.
> ![image](https://github.com/user-attachments/assets/4d9b88b1-4a37-465e-bacb-14daa775bedd)
> 

False is correct for activation conditions, midis default reaction prompt is being disabled in that context. Try turning on the debug setting in my module and check the console log for the actor silvery barbs should be triggering on

**Comment by MythicalRollers** [comment]
It does work, I figured out that it does not prompt if a token with its disposition of "Friendly" attack another "Friendly".

**Comment by gambit07** [comment]
> It does work, but only hostile to friendly, I figured out that it does not prompt if a token with its disposition of "Friendly" attacks another "Friendly". 

Yep that is correct, the debug log is helpful for figuring out issues like that. Most of my automations will not work for allied pvp since it creates way too many dialogs for players without much benefit
