### ISSUE TITLE
Upgraded to DnD 5e to V4 and Gambit's Pre-mades are no longer selectable

### ISSUE THREAD

**Issue by MadeeBeez** [gambit07/gambits-premades#33]
I upgraded to DnD 5e to V4 today (9/13/24) and Gambit's Premades are no longer selectable

**Comment by gambit07** [comment]
> I upgraded to DnD 5e to V4 today (9/13/24) and Gambit's Premades are no longer selectable

Yep it just came out today, gps will not be compatible with it for some time
