### ISSUE TITLE
Opportunity Attack is Triggered for a Token that is Invisible. 

### ISSUE THREAD

**Issue by mds0001** [gambit07/gambits-premades#34]
In the latest version. 0.5.45, When Opportunity Attack is enabled, an AoO fires off when a token with the Invisible effect is active. That seems to violate rules as written. 
![image](https://github.com/user-attachments/assets/81bc7c75-22d8-459c-a210-7c76400f7715)

**Comment by gambit07** [comment]
> In the latest version. 0.5.45, When Opportunity Attack is enabled, an AoO fires off when a token with the Invisible effect is active. That seems to violate rules as written. ![image](https://private-user-images.githubusercontent.com/7282827/368743017-81bc7c75-22d8-459c-a210-7c76400f7715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2OTk2MzUsIm5iZiI6MTcyNjY5OTMzNSwicGF0aCI6Ii83MjgyODI3LzM2ODc0MzAxNy04MWJjN2M3NS0yMmQ4LTQ1OWMtYTIxMC03Yzc2NDAwZjc3MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMjI0MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg5ODY1NjVkMDAyYjliOTQ3ZjczZmI1MDI3YjY1NTc2NWZjOGRmOGVmZDE4YWIxYmI1OWNhOWUwNDc1ZTUwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nm_BdpGW7Vk1DryZmaMfzXBctIugpUaYLcJO5hssSGQ)

Hi there, I can't replicate this. Are you using Chris Premades? If so, you may have a setting turned on that is causing this behavior:

Game Mechanic Options -> Disable Special Effects

**Comment by mds0001** [comment]
> > In the latest version. 0.5.45, When Opportunity Attack is enabled, an AoO fires off when a token with the Invisible effect is active. That seems to violate rules as written. ![image](https://private-user-images.githubusercontent.com/7282827/368743017-81bc7c75-22d8-459c-a210-7c76400f7715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2OTk2MzUsIm5iZiI6MTcyNjY5OTMzNSwicGF0aCI6Ii83MjgyODI3LzM2ODc0MzAxNy04MWJjN2M3NS0yMmQ4LTQ1OWMtYTIxMC03Yzc2NDAwZjc3MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMjI0MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg5ODY1NjVkMDAyYjliOTQ3ZjczZmI1MDI3YjY1NTc2NWZjOGRmOGVmZDE4YWIxYmI1OWNhOWUwNDc1ZTUwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nm_BdpGW7Vk1DryZmaMfzXBctIugpUaYLcJO5hssSGQ)
> 
> Hi there, I can't replicate this. Are you using Chris Premades? If so, you may have a setting turned on that is causing this behavior:
> 
> Game Mechanic Options -> Disable Special Effects
> 

I'll check it out.

**Comment by mds0001** [comment]
Correct. Resolved with suggested change in CPS. Thanks.

**Comment by mds0001** [comment]
Applied suggested setting. Now AoO, doesn't work at all. Even if the CPS setting is restored to original state. So no AoO at all. :(

**Comment by mds0001** [comment]
Thanks for the quick response. That setting did not seem to have any effect on the issue. Any other ideas?
