### ISSUE TITLE
Opportunity attack automation breaks Level module

### ISSUE THREAD

**Issue by SilvesTheRog** [gambit07/gambits-premades#35]
Hello!
Recently, I encountered an issue where enabled automation of opportunity attack somehow affects token elevation when Levels module is enabled.

I recorded a video that demonstrates the problem. Long story short, when the combat begins, all tokens' elevation changes, they go to the next level of the Levels module. When a token moves near any token (elevation or hidden status don't matter), it changes the elevation of adjacent tokens. Disabling automation of opportunity attacks actually solved the problem. 

https://youtu.be/b3CKI_rVPAY

**Comment by gambit07** [comment]
Hi there, does this occur with only Gambit's Premades plus dependencies?

**Comment by SilvesTheRog** [comment]
Yes. I suspect the reason is the region that appears when the combat begins. I did not put it manually there, it appears automatically when the combat begins. It appears only around those tokens that rolled initiative
![image](https://github.com/user-attachments/assets/49010530-60ba-41cb-9d78-6a96c6cb1fa5)

**Comment by SilvesTheRog** [comment]
![image](https://github.com/user-attachments/assets/de802208-d35a-4c6a-93c7-825e0eab64c2)

The region's name is "Levels Stairs 30-60". Maybe the Gambit's premades just draws the region, but Levels overrides it and makes it stairs?

**Comment by SilvesTheRog** [comment]
Okay, yeah, that's the issue. Disabling "Place drawings as stairs" makes the OA region appear instead of stairs. I suppose it's just the Levels issue, then.
![image](https://github.com/user-attachments/assets/19c70f61-f6ee-40cb-9681-18a39e483a76)

**Comment by gambit07** [comment]
> Okay, yeah, that's the issue. Disabling "Place drawings as stairs" makes the OA region appear instead of stairs. I suppose it's just the Levels issue, then. 
> Would be great if GP's regions could override the Levels' regions somehow. Because "Place drawings as stairs" is enabled by default and automatically enables every time the world launches. 
> ![image](https://github.com/user-attachments/assets/19c70f61-f6ee-40cb-9681-18a39e483a76)
> 

Interesting, this seems like a levels bug. Place drawings as stairs calls out drawings specifically. Those shouldn't have an interaction with regions at all based off the name. Might want to check in with ripper on that one

**Comment by SilvesTheRog** [comment]
Yeah, I checked his discord and found out it's not a bug. He said if you create a region with the levels ui open it will make the region into a stair (and it requires enabling "Place Drawings as Stairs", which is enabled by default). 
I sent the public feature request to either disable this setting by default, or at least don't re-enable it after refreshing foundry or launching a world. For now, the solution is to disable the "Place Drawings as Stairs" manually. I guess the issue can be closed now, since it's not a bug, but an unpleasant interaction between two modules. Thank you!

**Comment by gambit07** [comment]
> Yeah, I checked his discord and found out it's not a bug. He said if you create a region with the levels ui open it will make the region into a stair (and it requires enabling "Place Drawings as Stairs", which is enabled by default). 
> I sent the public feature request to either disable this setting by default, or at least don't re-enable it after refreshing foundry or launching a world. For now, the solution is to disable the "Place Drawings as Stairs" manually. I guess the issue can be closed now, since it's not a bug, but an unpleasant interaction between two modules. Thank you!

Odd, does this only happen if combat starts while the levels editor is open?

**Comment by SilvesTheRog** [comment]
This happens when the combat starts because the OA region appears on the token (image 1). But if Levels' "Place Drawings as Stairs" is enabled, then this region is replaced with stairs (image 2), making the token and everything inside the region instantly go to the next floor. Moving around also makes nearby tokens change their elevation since the region is attached to the token and the nearby tokens "enter" the region. 
![image](https://github.com/user-attachments/assets/eee077bd-6135-4df5-898d-9cf7cc0729fb)
![image](https://github.com/user-attachments/assets/d6046018-f48e-463f-b5af-3fe6d27e9997)

**Comment by gambit07** [comment]
Does this only occur on a scene where levels are implemented? I've had levels enabled in the past without this happening, but I don't think I was actively using any levels on scenes at that time

**Comment by SilvesTheRog** [comment]
Yes, there are no issues when testing on a map without any levels, even with the "Place Drawings as Stairs" enabled
![image](https://github.com/user-attachments/assets/8d1dd2a5-70ea-4275-98a5-6283ddd652e2)

**Comment by gambit07** [comment]
> Yes, there are no issues when testing on a map without any levels, even with the "Place Drawings as Stairs" enabled
> ![image](https://github.com/user-attachments/assets/8d1dd2a5-70ea-4275-98a5-6283ddd652e2)
> 

Thanks, checking in with ripper to see if there's anything I can do about that

**Comment by gambit07** [comment]
> Yes, there are no issues when testing on a map without any levels, even with the "Place Drawings as Stairs" enabled ![image](https://private-user-images.githubusercontent.com/127493227/369620836-8d1dd2a5-70ea-4275-98a5-6283ddd652e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjYxMDksIm5iZiI6MTcyNjkyNTgwOSwicGF0aCI6Ii8xMjc0OTMyMjcvMzY5NjIwODM2LThkMWRkMmE1LTcwZWEtNDI3NS05OGE1LTYyODNkZGQ2NTJlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMzM2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2E1MzliNTlkNzBmMDVlZjkyZTkwNDVmNWViMmUxZjZiYzMwYWIzMzVhZTIzMTE1YmU1YTU3NzY3MTJkOTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8uRckLMWPczuFbegVLKxXwEnH0SLhPE4zwDmCc8osSE)

It sounds like this won't occur if the Levels Layer Tool is not open during combat. I'd just make sure you only have that tool open when you're building a level, and make sure to close it otherwise

**Comment by gambit07** [comment]
I'm going to add a workaround for this based on Rippers feedback to avoid people having issues with it in the future. Keep in mind other things may be effected by having that UI open though (Region Attacher comes to mind), so you may still run into issues elsewhere. My recommendation would still be to try and keep the levels tool closed during combat
