### ISSUE TITLE
[Feature request] Ability to remove "Template preview tool" from the toolbar

### ISSUE THREAD

**Issue by TrofimSelbs** [gambit07/gambits-premades#38]
Hello Gambit! Thank you for your module and automation, running opportunity attacks before this module was tough. So thank you for that! I come here asking if you could please add an ability in the settings of the module to remove this button from the toolbar. I never use it, at least right now, and it would be nice to have the ability to tidy up the toolbar. Thank you in advance 

![image](https://github.com/user-attachments/assets/cfa7e894-e055-4779-bae8-04625ba5821e)

**Comment by gambit07** [comment]
> Hello Gambit! Thank you for your module and automation, running opportunity attacks before this module was tough. So thank you for that! I come here asking if you could please add an ability in the settings of the module to remove this button from the toolbar. I never use it, at least right now, and it would be nice to have the ability to tidy up the toolbar. Thank you in advance
> 
> ![image](https://private-user-images.githubusercontent.com/124184162/382512904-cfa7e894-e055-4779-bae8-04625ba5821e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mzc3NDksIm5iZiI6MTczMDczNzQ0OSwicGF0aCI6Ii8xMjQxODQxNjIvMzgyNTEyOTA0LWNmYTdlODk0LWUwNTUtNDc3OS1iYWU4LTA0NjI1YmE1ODIxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxNjI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzExMjZhNzUzYTFlZTViYzEwNzhhYjQ5Nzc4MzIwNGU0ZjZkNjA4ZTcxZGE0NDc2NjJiMTQwZTlhYzk4ODk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SUcKkH7XlspDu6CpVE5UMK7RvIcm9bTvS8wTsTDoWFU)

Hi there, yes this can be disabled under my modules settings in General Settings

**Comment by TrofimSelbs** [comment]
I looked for it 3 times lol. Thanks 👋
