### ISSUE TITLE
Throwing torch requires owner permission on default item pile actor

### ISSUE THREAD

**Issue by Creep2342** [gambit07/gambits-premades#40]
I really like the way you handle the torches. 
When non-gm players try to throw the torch, they get a permission error by default.
This error goes away if I give them owner permission to the "default item pile" actor. This is not a great solution though, because it would mean they gain visibility for every dropped item/item pile in the scene.
Is there something I am missing?
Could the macro summon a specific torch-actor instead of creating a default item pile?

Foundry v12.331
DnD 3.3.1
Gambit 0.5.86
Item Piles 3.16

Best Regards

**Comment by gambit07** [comment]
Good to know thanks, I'll take a look

**Comment by Creep2342** [comment]
These are the 2 error messages that pop up when a player tries to throw the torch:

```
foundry.js:72076 User Testy lacks permission to update Token [AmmRoTb5oQCxwU6j] in parent Scene [WNGdGDmHdfZln9Ae]
fetch @ foundry.js:72076
notify @ foundry.js:71972
🎁call_wrapped @ libWrapper-wrapper.js:511
notificationNotify @ utils.js:4668
🎁call_wrapper @ libWrapper-wrapper.js:639
🎁Notifications.prototype.notify#0 @ libWrapper-wrapper.js:193
error @ foundry.js:72009
#handleError @ foundry.js:3479
(anonymous) @ foundry.js:3462
value @ socket.js:580
value @ socket.js:499
U.emit @ index.mjs:136
(anonymous) @ manager.js:204
Promise.then
ce @ websocket-constructor.browser.js:5
value @ manager.js:203
U.emit @ index.mjs:136
value @ index.js:146
value @ manager.js:190
U.emit @ index.mjs:136
value @ socket.js:341
U.emit @ index.mjs:136
value @ transport.js:98
value @ transport.js:90
ws.onmessage @ websocket.js:68
```

```
VM6961:312 Failed to create item pile: Error: User Testy lacks permission to update Token [AmmRoTb5oQCxwU6j] in parent Scene [WNGdGDmHdfZln9Ae]
    at file:///C:/Games/Foundry/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5101
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (file:///C:/Games/Foundry/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (file:///C:/Games/Foundry/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)
createItemPileWithEffect @ VM6961:312
await in createItemPileWithEffect
callback @ VM6961:59
callback @ VM6961:129
_onSubmit @ foundry-esm.js:45542
_onClickButton @ foundry-esm.js:45595
#onClickAction @ foundry-esm.js:45097
#onClick @ foundry-esm.js:45058

```

This is the full UUID of the Torch-item-Pile that is currently on the ground:
Scene.WNGdGDmHdfZln9Ae.Token.V2VHkU71bpHSE4dT.Actor.D0ABQwcWOl9b2Cvs

For the moment I am using this workaround:
Inside the macro I have changed createActor: false to createActor: true
This way a new item pile actor sheet is created on each throw and the permission error does not occur.
I need to delete all remnant actor sheets at the end of the session tough.

**Comment by Creep2342** [comment]
btw when it breaks the item pile is already created on the ground, but does not yet use the image "modules/gambits-premades/assets/images/torch.webp"

so it might break right at the following line is what I am guessing:
`if(tokenData.texture.src !== FILE_PATH) await tokenData.update({"texture.src": FILE_PATH})`

**Comment by Creep2342** [comment]
Ah ok, If I make sure the inventory item is already using your above torch.webp from the get go it works.
Because the macro is never trying to run tokenData.update in that case.

**Comment by gambit07** [comment]
> Ah ok, If I make sure the inventory item is already using your above torch.webp from the get go it works. Because the macro is never trying to run tokenData.update in that case.

Cool, yeah I don't think I need that piece anyway, just had the initial token image incorrectly assigned. Should be fixed in the next update
