### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by Kharmans** [gambit07/gambits-premades#5]
The **Confusion** spell doesn't work properly on dnd5e 3.x. Some things that I notice:

If a creature roll a 2-6, it takes it's effects, with a Reaction mark on it, from midi porpuses. If it fails on the save, the effects are not still there, an that's okay. The thing is: when it turn comes again, all goes wrong. The effects applied from the d10 roll are not properly applied. If the creature roll a 2-6 again, it's reaction are not marked, if it roll anything besides a 2-6, it's movement are still 0, and the things go on and on.

Sometimes it just applies the wrong effect, like this:
![image](https://github.com/gambit07/gambits-premades/assets/112586547/c96ac8dd-61dd-4408-a887-91e8ba744b5f)
It should appliy the _"The creature doesn't move or take actions this turn."_

Another thing: if I translate anything on the macro, nothing works. I am translating only the things that are showed on chat cards. I don't know why this happens. The translate I did was that:

```
const lastArg = args[args.length - 1];
const tokenOrActor = await fromUuid(lastArg.actorUuid);
const targetActor = tokenOrActor.actor ? tokenOrActor.actor : tokenOrActor;

if (args[0] === "each") {

  const confusionRoll = await new CONFIG.Dice.DamageRoll("1d10").evaluate({ async: true });
  const result = confusionRoll.total;
  let content;
  switch (result) {
    case 1:
      content = "A criatura usa todo o seu deslocamento para se deslocar em uma direção aleatória. Para determinar a direção, jogue um [[d8]] e atribua uma direção para cada face do dado. A criatura não executa uma ação neste turno.";
      break;
    case 2:
      content = "A criatura não se move e nem executa ações neste turno.";
      break;
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      content = "A criatura usa sua ação para fazer um ataque corpo a corpo contra uma criatura determinada aleatoriamente dentro do alcance dela. Se não houver nenhuma criatura ao alcance dela, a criatura não faz nada neste turno.";
      break;
    case 8:
    case 9:
    case 10:
      content = "A criatura pode agir e mover-se normalmente.";
      break;
  }
  ChatMessage.create({ content: `A jogada de ${targetActor.name} foi ${result}:<br> ` + content });
}
```

And sometimes, the erro bellow just show on the console, right after the save roll.
![image](https://github.com/gambit07/gambits-premades/assets/112586547/bb931340-7401-4b0a-9a0d-e5b63e577fcd)

**Comment by gambit07** [comment]
Should be resolved in .69

**Comment by Kharmans** [comment]
Forget it, I am just an idiot who are doing wrong things.

The only thing that is okay for what I say is the Reaction thing.

**Comment by gambit07** [comment]
> Forget it, I am just an idiot who are doing wrong things.
> 
> The only thing that is okay for what I say is the Reaction thing.

No problem, the rewrite fixed a few issues and I added native localization so the chat outputs should display the language correctly
