### ISSUE TITLE
Chain Lightning

### ISSUE THREAD

**Issue by Kharmans** [gambit07/gambits-premades#6]
When the window to choose other targets is show, it doesn't highlight the actors I am choosing. If I have more than one actor with the same name, I don't know who of then I am choosing.

![image](https://github.com/gambit07/gambits-premades/assets/112586547/ff02920b-d578-450c-9049-762031db6ff3)

And if I choose more targets than the level of the spell let, it just close it and nothing happens, no error on console.

**Comment by gambit07** [comment]
Hi, I don't have Chain Lightning in my module, you might  be thinking of Chris Premades
