### ISSUE TITLE
Stinking Cloud

### ISSUE THREAD

**Issue by Kharmans** [gambit07/gambits-premades#7]
The spell are not configure with Concentration. When you manually change that to Concentration, it apply the Concentration to the caster, but to actors that fail on the save too.

**Comment by Kharmans** [comment]
**D&D5e**: v3.0.3
**Gambit's Premades**: v0.0.79
**MidiQOL**: v11.4.5
**DAE**: v11.3.8

**Comment by gambit07** [comment]
Ah I think I forgot this one required concentration, will have a look at it

**Comment by gambit07** [comment]
> The spell are not configure with Concentration. When you manually change that to Concentration, it apply the Concentration to the caster, but to actors that fail on the save too.

This will be resolved in .84
