### ISSUE TITLE
Paladin: Divine sense

### ISSUE THREAD

**Issue by k3tw13z3l** [gambit07/gambits-premades#8]
It looks like that if the Paladin can't see the target, it can also not 'divine sense' the target...

So a target within range but unseen due tobeing  'hidden' or light conditions is not sensed (at least no visual cue). 

foundry: 11.315
DND5e :3.03
midi 11.4.7
GP: 0.0.84 (the item says 0.0.57)

**Comment by gambit07** [comment]
I added some support to allow the chat card to output properly, will need additional work to try and support it visually

**Comment by gambit07** [comment]
> It looks like that if the Paladin can't see the target, it can also not 'divine sense' the target...
> 
> So a target within range but unseen due tobeing 'hidden' or light conditions is not sensed (at least no visual cue).
> 
> foundry: 11.315 DND5e :3.03 midi 11.4.7 GP: 0.0.84 (the item says 0.0.57)

Full support for vision added in .87
